apiVersion: v1
kind: Pod
metadata:
  name: dastardly-scan
  namespace: aeon
spec:
  restartPolicy: Never
  containers:
    - name: dastardly
      image: public.ecr.aws/portswigger/dastardly:latest
      imagePullPolicy: IfNotPresent
      env:
        - name: BURP_START_URL
          value: "http://aeon.aeon.svc.cluster.local:4471/"
        - name: BURP_REPORT_FILE_PATH
          value: "/dastardly/report.xml"
      volumeMounts:
        - name: reports
          mountPath: /dastardly
    - name: helper
      image: busybox:latest
      imagePullPolicy: IfNotPresent
      command: ["sh", "-c", "sleep 3600"]
      volumeMounts:
        - name: reports
          mountPath: /dastardly
  volumes:
    - name: reports
      emptyDir: {}
