apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  labels:
    app.kubernetes.io/name: aeon
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: api
      port: {{ .Values.ports.api }}
      targetPort: api
      protocol: TCP
    - name: metrics
      port: {{ .Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
    - name: quic
      port: {{ .Values.ports.quic }}
      targetPort: quic
      protocol: UDP
  selector:
    app.kubernetes.io/name: aeon
    app.kubernetes.io/instance: {{ .Release.Name }}
